attributes :id,
           :email,
           :fname,
           :mname,
           :lname,
           :verified,
           :adhaar_no,
           :created_by,
           :updated_by,
           :avatar,
           :login,
           :phone1,
           :addr1,
           :addr2,
           :addr3,
           :addr4
           