development:
  smtp: &SMTP
    allow_outgoing_emails: false
    mailgun: &MAILGUN
      port: 587
      address: "smtp.mailgun.com"
      user_name: "postmaster@sandbox4907475c71f140c59e9e171c38e00093.mailgun.org"
      password: "1d018f2be83dfbd9b9df89d6c603e71d"
      from: "info@h4r.com" #"abedali@sandbox4907475c71f140c59e9e171c38e00093.mailgun.org"
      api_key: "key-670fe0e29a970cadf2a5f2c170f23992"
      domain: "sandbox4907475c71f140c59e9e171c38e00093.mailgun.org"
  date_format: "%d-%m-%Y"
  ADMIN_DEFAULT_SUBSCRIPTION: 5
  SUBSCRIPTION_GOOD_FOR: 6 #any promoted subscription is good for 6 months
  AWS_KEY: <%= ENV['AWS_KEY'] %>
  AWS_SECRET: <%= ENV['AWS_SECRET'] %>
  AWS_REGION: <%= ENV['AWS_REGION'] %> #Ohio doesn't have couldsearch
  AWS_CS_REGION: <%= ENV['AWS_CS_REGION'] %> #CS-CloudSearch region
  CS_DOMAIN_NAME: <%= ENV['CS_DOMAIN_NAME'] %>
  CS_UPLOAD_DOCS_ENDPOINT: <%= ENV['CS_UPLOAD_DOCS_ENDPOINT'] %>
  CS_SEARCH_DOCS_ENDPOINT: <%= ENV['CS_SEARCH_DOCS_ENDPOINT'] %>
  CLIENT_DOMAIN: <%= ENV['FRONT_END_DOMAIN_URL'] %>
  
production:
  date_format: "%d-%m-%Y"
  ADMIN_DEFAULT_SUBSCRIPTION: 5
  SUBSCRIPTION_GOOD_FOR: 3 #The new subscription is good for 6 months
