attributes :id,
           :name, 
           :addr1, 
           :addr2, 
           :addr3, 
           :addr4, 
           :no_of_portions, 
           :no_of_floors, 
           :verified, 
           :processing_fee,
           :community_id,
           :active,
           :created_by,
           :updated_by,
           :created_at, :updated_at,
           :description